plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'top.nkbe.art'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "top.nkbe.art"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug() {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
    ndkVersion "29.0.13846066"
    defaultConfig {
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    splits {
        abi {
            enable false
        }
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
    buildFeatures {
        compose true
    }
}

configurations.configureEach {
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk7"
    exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib-jdk8"
}

dependencies {
    implementation fileTree(dir:'libs',include:['*.jar'])
    implementation 'com.android.tools.smali:smali-dexlib2:3.0.9'
    implementation "androidx.activity:activity-compose:1.13.0"
    implementation platform("androidx.compose:compose-bom:2026.05.00")
    implementation "androidx.compose.foundation:foundation"
    implementation "androidx.compose.ui:ui-tooling-preview"
    debugImplementation "androidx.compose.ui:ui-tooling"
    implementation "io.github.suqi8.coui.kmp:coui-ui:1.0.0"
    implementation 'com.github.TimScriptov:apksigner:1.2.0'
    implementation 'org.bouncycastle:bcprov-jdk15to18:1.78.1'
    testImplementation libs.junit
    //implementation "androidx.appcompat:appcompat:1.7.0"
    //implementation libs.material

}
